_commit: v1.4.0
_src_path: C:/prj/p2p/ongithub/aatemplate
project_name: many-panelz-explorer
package_name: many_panelz_explorer
description: Multi-panel Windows-focused file explorer built with PySide6
author_name: MT0z
author_email: mt0z1@pir0z.yxz
github_username: Threepwood-7
project_version: 0.1.0
runtime_dependencies:
- PySide6>=6.10.2
- send2trash
